import request from './request'

export const getPartners = (params) => request.get('/partners', { params })
export const getPartner = (id) => request.get(`/partners/${id}`)
export const createPartner = (data) => request.post('/partners', data)
export const updatePartner = (id, data) => request.put(`/partners/${id}`, data)
export const deletePartner = (id) => request.delete(`/partners/${id}`)
export const getPartnerOptions = () => request.get('/partners/options')

export const getContacts = (params) => request.get('/contacts', { params })
export const getContact = (id) => request.get(`/contacts/${id}`)
export const createContact = (data) => request.post('/contacts', data)
export const updateContact = (id, data) => request.put(`/contacts/${id}`, data)
export const deleteContact = (id) => request.delete(`/contacts/${id}`)
export const getContactRoles = () => request.get('/contacts/roles')

export const getProducts = (params) => request.get('/products', { params })
export const getProduct = (id) => request.get(`/products/${id}`)
export const createProduct = (data) => request.post('/products', data)
export const updateProduct = (id, data) => request.put(`/products/${id}`, data)
export const deleteProduct = (id) => request.delete(`/products/${id}`)
export const getProductCategories = () => request.get('/products/categories')
export const getProductStatuses = () => request.get('/products/statuses')

export const getProjects = (params) => request.get('/projects', { params })
export const getProject = (id) => request.get(`/projects/${id}`)
export const createProject = (data) => request.post('/projects', data)
export const updateProject = (id, data) => request.put(`/projects/${id}`, data)
export const deleteProject = (id) => request.delete(`/projects/${id}`)
export const getProjectStages = () => request.get('/projects/stages')

export const getContracts = (params) => request.get('/contracts', { params })
export const getContract = (id) => request.get(`/contracts/${id}`)
export const createContract = (data) => request.post('/contracts', data)
export const updateContract = (id, data) => request.put(`/contracts/${id}`, data)
export const deleteContract = (id) => request.delete(`/contracts/${id}`)
export const getContractTypes = () => request.get('/contracts/types')
export const getContractStatuses = () => request.get('/contracts/statuses')

export const getFollowups = (params) => request.get('/followups', { params })
export const getFollowup = (id) => request.get(`/followups/${id}`)
export const createFollowup = (data) => request.post('/followups', data)
export const updateFollowup = (id, data) => request.put(`/followups/${id}`, data)
export const deleteFollowup = (id) => request.delete(`/followups/${id}`)
export const getFollowupMethods = () => request.get('/followups/methods')

export const getBusinessTerms = (params) => request.get('/business-terms', { params })
export const getBusinessTerm = (id) => request.get(`/business-terms/${id}`)
export const createBusinessTerm = (data) => request.post('/business-terms', data)
export const updateBusinessTerm = (id, data) => request.put(`/business-terms/${id}`, data)
export const deleteBusinessTerm = (id) => request.delete(`/business-terms/${id}`)
export const getTermTypes = () => request.get('/business-terms/types')
export const getTermStatuses = () => request.get('/business-terms/statuses')

export const getQualifications = (params) => request.get('/qualifications', { params })
export const getQualification = (id) => request.get(`/qualifications/${id}`)
export const createQualification = (data) => request.post('/qualifications', data)
export const updateQualification = (id, data) => request.put(`/qualifications/${id}`, data)
export const deleteQualification = (id) => request.delete(`/qualifications/${id}`)
export const getQualificationNames = () => request.get('/qualifications/names')
export const getExpiringQualifications = (days) => request.get('/qualifications/expiring', { params: { days } })

export const getUsers = (params) => request.get('/users', { params })
export const getUser = (id) => request.get(`/users/${id}`)
export const createUser = (data) => request.post('/users', data)
export const updateUser = (id, data) => request.put(`/users/${id}`, data)
export const deleteUser = (id) => request.delete(`/users/${id}`)
export const getRoles = () => request.get('/users/roles')
export const getUserOptions = () => request.get('/users/options')